name: DEPLOY FRONTEND

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker buildx build -t thashree11/bookstore-frontend .


      - name: Publish Image to DockerHub
        run: docker push thashree11/bookstore-frontend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: docker pull thashree11/thashree11/bookstore-frontend:latest

      - name: Delete Container
        run: docker rm -f frontend-container

      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name frontend-container thashree11/bookstore-frontend
