name: DEPLOY FRONTEND

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: sudo docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: sudo docker buildx build -t thashree11/bookstore-frontend .


      - name: Publish Image to DockerHub
        run: sudo docker push thashree11/bookstore-frontend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: sudo docker pull thashree11/bookstore-frontend:latest

      - name: Delete Container
        run: sudo docker rm -f frontend-container

      - name: Run Docker Container
        run: sudo docker run -d -p 5173:80 --name frontend-container thashree11/bookstore-frontend
